src/GamesExchange/src/GamesExchange.WebMvc/Models/PaginationViewModel.cs
using GamesExchange.Application.lib;

namespace GamesExchange.WebMvc.Models
{
    public class PaginationViewModel
    {
        public string Url { get; set; }
        public PageSummary Summary { get; set; }
    }
}

src/GamesExchange/src/GamesExchange.WebMvc/Controllers/FriendsController.cs
using GamesExchange.Application.lib;
using GamesExchange.Model.Games;
using GamesExchange.Model.Identification;
using GamesExchange.WebMvc.Models;

using Microsoft.AspNetCore.Mvc;

using Person = GamesExchange.Application.Identification.Person;

namespace GamesExchange.WebMvc.Controllers
{
    public class FriendsController : Controller
    {
        private readonly Person.List.IUseCase listUseCase;
        private readonly Person.Create.IUseCase createUseCase;
        private readonly Person.Edit.IUseCase editUseCase;
        private readonly Person.Delete.IUseCase deleteUseCase;
        private readonly Person.GetById.IUseCase getByIdUseCase;

        public FriendsController(Person.List.IUseCase listUseCase, Person.Create.IUseCase createUseCase, Person.Edit.IUseCase editUseCase, 
            Person.Delete.IUseCase deleteUseCase, Person.GetById.IUseCase getByIdUseCase)
        {
            this.listUseCase = listUseCase;
            this.createUseCase = createUseCase;
            this.editUseCase = editUseCase;
            this.deleteUseCase = deleteUseCase;
            this.getByIdUseCase = getByIdUseCase;
        }

        public async Task<IActionResult> Index(PersonFilter? filter, PageSummary? summary)
        {
            summary.PageNumber = summary.PageNumber == 0 ? 1 : summary.PageNumber;
            summary.PageSize = summary.PageSize == 0 ? 10 : summary.PageSize;

            var input = new Person.List.Input { Filter = filter, Summary = summary };

            var result = await listUseCase.Execute(input);

            var pagination = new PaginationViewModel
            {
                Summary = result.Summary,
                Url = Url.Action("Index") + filter.ToQueryString()
            };

            var viewModel = new FriendsListViewModel
            {
                Data = result.Data,
                Filter = filter,
                Pagination = pagination
            };

            return View(viewModel);
        }

        public IActionResult Create()
        {
            var viewModel = new FriendsFormViewModel();

            return View("Form", viewModel);
        }

        public async Task<IActionResult> Edit(long id)
        {
            var viewModel = new FriendsFormViewModel();

            var result = await getByIdUseCase.Execute(new Person.GetById.Input { Id = id });

            viewModel.Id = id;
            viewModel.FirstName = result.Data.FirstName;
            viewModel.LastName = result.Data.LastName;
            viewModel.Email = result.Data.Email;
            viewModel.CellNumber = result.Data.CellNumber;
            viewModel.PhoneNumber = result.Data.PhoneNumber;

            return View("Form", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Save(FriendsFormViewModel viewModel)
        {
            if (viewModel.Id == 0)
            {
                var input = new Person.Create.Input
                {
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Email = viewModel.Email,
                    CellNumber = viewModel.CellNumber,
                    PhoneNumber = viewModel.PhoneNumber
                };

                _ = await createUseCase.Execute(input);
            }
            else
            {
                var input = new Person.Edit.Input
                {
                    Id = viewModel.Id,
                    FirstName = viewModel.FirstName,
                    LastName = viewModel.LastName,
                    Email = viewModel.Email,
                    CellNumber = viewModel.CellNumber,
                    PhoneNumber = viewModel.PhoneNumber
                };

                _ = await editUseCase.Execute(input);
            }

           return RedirectToAction("Index");
        }
    }
}

src/GamesExchange/src/GamesExchange.WebMvc/Controllers/GamesController.cs
using GamesExchange.Application.lib;
using GamesExchange.Model.Games;
using Game = GamesExchange.Application.Games.Game;

using Microsoft.AspNetCore.Mvc;
using GamesExchange.WebMvc.Models;
using GamesExchange.Model.Identification;

namespace GamesExchange.WebMvc.Controllers
{
    public class GamesController : Controller
    {
        private readonly Game.List.IUseCase listUseCase;
        private readonly Game.Create.IUseCase createUseCase;
        private readonly Game.Edit.IUseCase editUseCase;
        private readonly Game.Delete.IUseCase deleteUseCase;
        private readonly Game.GetById.IUseCase getByIdUseCase;

        public GamesController(Game.List.IUseCase listUseCase, Game.Create.IUseCase createUseCase, Game.Edit.IUseCase editUseCase, 
            Game.Delete.IUseCase deleteUseCase, Game.GetById.IUseCase getByIdUseCase)
        {
            this.listUseCase = listUseCase;
            this.createUseCase = createUseCase;
            this.editUseCase = editUseCase;
            this.deleteUseCase = deleteUseCase;
            this.getByIdUseCase = getByIdUseCase;
        }

        public async Task<IActionResult> Index(GameFilter? filter, PageSummary? summary)
        {
            summary.PageNumber = summary.PageNumber == 0 ? 1 : summary.PageNumber;
            summary.PageSize = summary.PageSize == 0 ? 10 : summary.PageSize;

            var input = new Game.List.Input { Filter = filter, Summary = summary };

            var result = await listUseCase.Execute(input);
            
            var pagination = new PaginationViewModel
            {
                Summary = result.Summary,
                Url = Url.Action("Index") + filter.ToQueryString()
            };

            var viewModel = new GameListViewModel
            {
                Data = result.Data,
                Filter = filter,
                Pagination = pagination
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new GameFormViewModel();

            return View("Form", viewModel);
        }

        public async Task<IActionResult> Edit(long id)
        {
            var viewModel = new GameFormViewModel();
            var result = await getByIdUseCase.Execute(new Game.GetById.Input { Id = id });

            viewModel.Id = id;
            viewModel.Name = result.Data.Name;
            viewModel.Description = result.Data.Description;
            viewModel.Console = result.Data.Console;
            viewModel.Studio = result.Data.Studio;
            viewModel.OwnerId = result.Data.OwnerId;
            viewModel.Price = result.Data.Price;

            return View("Form", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Save(GameFormViewModel viewModel)
        {
            if (viewModel.Id == 0)
            {
                var input = new Game.Create.Input
                {
                    Name = viewModel.Name,
                    Description = viewModel.Description,
                    Console = viewModel.Console,
                    Studio = viewModel.Studio,
                    OwnerId = viewModel.OwnerId,
                    Price = viewModel.Price
                };

                _ = await createUseCase.Execute(input);
            }
            else
            {
                var input = new Game.Edit.Input
                {
                    Id = viewModel.Id,
                    Name = viewModel.Name,
                    Description = viewModel.Description,
                    Console = viewModel.Console,
                    Studio = viewModel.Studio,
                    OwnerId = viewModel.OwnerId,
                    Price = viewModel.Price
                };

                _ = await editUseCase.Execute(input);
            }

            return RedirectToAction("Index");
        }
    }
}

src/GamesExchange/src/GamesExchange.WebMvc/Controllers/UsersController.cs
using GamesExchange.Application.lib;
using GamesExchange.Model.Identification;
using GamesExchange.WebMvc.Models;

using Microsoft.AspNetCore.Mvc;

using User = GamesExchange.Application.Identification.User;
using Person = GamesExchange.Application.Identification.Person;

namespace GamesExchange.WebMvc.Controllers
{
    public class UsersController : Controller
    {
        private readonly User.List.IUseCase listUseCase;
        private readonly User.Create.IUseCase createUseCase;
        private readonly User.Edit.IUseCase editUseCase;
        private readonly User.Delete.IUseCase deleteUseCase;
        private readonly User.GetById.IUseCase getByIdUseCase;
        private readonly Person.ListAllToDictionary.IUseCase personListAllToDictionaryUseCase;

        public UsersController(User.List.IUseCase listUseCase, User.Create.IUseCase createUseCase, User.Edit.IUseCase editUseCase,
            User.Delete.IUseCase deleteUseCase, User.GetById.IUseCase getByIdUseCase, 
            Person.ListAllToDictionary.IUseCase personListAllToDictionaryUseCase)
        {
            this.listUseCase = listUseCase;
            this.createUseCase = createUseCase;
            this.editUseCase = editUseCase;
            this.deleteUseCase = deleteUseCase;
            this.getByIdUseCase = getByIdUseCase;
            this.personListAllToDictionaryUseCase = personListAllToDictionaryUseCase;
        }

        public async Task<IActionResult> Index(UserFilter? filter, PageSummary? summary)
        {
            summary.PageNumber = summary.PageNumber == 0 ? 1 : summary.PageNumber;
            summary.PageSize = summary.PageSize == 0 ? 10 : summary.PageSize;

            var input = new User.List.Input { Filter = filter, Summary = summary };

            var result = await listUseCase.Execute(input);

            var pagination = new PaginationViewModel
            {
                Summary = result.Summary,
                Url = Url.Action("Index") + filter.ToQueryString()
            };

            var viewModel = new UserListViewModel
            {
                Data = result.Data,
                Filter = filter,
                Pagination = pagination
            };

            return View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            var viewModel = new UserFormViewModel();
            await LoadPeople(viewModel);

            return View("Form", viewModel);
        }

        public async Task<IActionResult> Edit(long id)
        {
            var viewModel = new UserFormViewModel();
            await LoadPeople(viewModel);

            var result = await getByIdUseCase.Execute(new User.GetById.Input { Id = id });

            viewModel.Id = id;
            viewModel.PersonId = result.Data.PersonId;
            viewModel.Username = result.Data.Username;
            viewModel.Active = result.Data.Active;
            viewModel.Role = result.Data.Role;

            return View("Form", viewModel);
        }

        private async Task LoadPeople(UserFormViewModel viewModel)
        {
            var result = await personListAllToDictionaryUseCase.Execute(new Person.ListAllToDictionary.Input());
            viewModel.People = result.Data;
        }

        [HttpPost]
        public async Task<IActionResult> Save(UserFormViewModel viewModel)
        {
            if (viewModel.Id == 0)
            {
                var input = new User.Create.Input
                {
                    PersonId = viewModel.PersonId,
                    Username = viewModel.Username,
                    Password = viewModel.Password,
                    Active = viewModel.Active,
                    Role = viewModel.Role
                };

                _ = await createUseCase.Execute(input);
            }
            else
            {
                var input = new User.Edit.Input
                {
                    Id = viewModel.Id,
                    PersonId = viewModel.PersonId,
                    Username = viewModel.Username,
                    Password = viewModel.Password,
                    Active = viewModel.Active,
                    Role = viewModel.Role
                };

                _ = await editUseCase.Execute(input);
            }

            return RedirectToAction("Index");
        }
    }
}

src/GamesExchange/src/GamesExchange.WebMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="loading dark-layout" lang="pt-br" data-textdirection="ltr">
<!-- BEGIN: Head-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=0,minimal-ui">
    <title>@ViewData["Title"] - Games Exchange</title>
    <link rel="apple-touch-icon" href="~/app-assets/images/ico/apple-icon-120.png">
    <link rel="shortcut icon" type="image/x-icon" href="~/app-assets/images/ico/favicon.ico">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;1,400;1,500;1,600" rel="stylesheet">

    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/vendors/css/vendors.min.css">
    <!-- END: Vendor CSS-->
    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/bootstrap-extended.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/colors.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/components.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/themes/dark-layout.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/themes/bordered-layout.css">
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/themes/semi-dark-layout.css">

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="~/app-assets/css/core/menu/menu-types/vertical-menu.css">
    <!-- END: Page CSS-->
    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css">

    <!-- END: Custom CSS-->

</head>
<!-- END: Head-->
<!-- BEGIN: Body-->

<body class="vertical-layout vertical-menu-modern  navbar-floating footer-static" data-open="click" data-menu="vertical-menu-modern" data-col="">
    <!-- BEGIN: Header-->
    <nav class="header-navbar navbar navbar-expand-lg align-items-center floating-nav navbar-light navbar-shadow">
        <div class="navbar-container d-flex content">
            <ul class="nav navbar-nav align-items-center ml-auto">
                <li class="nav-item">
                    <a class="nav-link"  href="@Url.Action("LogOut","Login")">
                        <div class="d-sm-flex d-none">
                            <span class="user-name font-weight-bolder">Saír</span>
                        </div>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- END: Header-->
    <partial name="_Menu.cshtml" />
    <!-- BEGIN: Content-->
    <div class="app-content content ">
        <div class="content-overlay"></div>
        <div class="header-navbar-shadow"></div>
        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    <!-- END: Content-->

    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>

    <!-- BEGIN: Footer-->
    <footer class="footer footer-static footer-light">
       
    </footer>
    <button class="btn btn-primary btn-icon scroll-top" type="button"><i data-feather="arrow-up"></i></button>
    <!-- END: Footer-->
    <!-- BEGIN: Vendor JS-->
    <script src="~/app-assets/vendors/js/vendors.min.js"></script>
    <!-- BEGIN Vendor JS-->
    <!-- BEGIN: Page Vendor JS-->
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Theme JS-->
    <script src="~/app-assets/js/core/app-menu.js"></script>
    <script src="~/app-assets/js/core/app.js"></script>
    <!-- END: Theme JS-->
    <!-- BEGIN: Page JS-->
    <!-- END: Page JS-->
    @RenderSection("Scripts", required: false)
    <script>
        $(window).on('load', function () {
            if (feather) {
                feather.replace({
                    width: 14,
                    height: 14
                });
            }
        })
    </script>
</body>
<!-- END: Body-->

</html>

src/GamesExchange/src/GamesExchange.WebMvc/Views/Shared/_Menu.cshtml
<!-- BEGIN: Main Menu-->
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="navbar-header">
        <ul class="nav navbar-nav flex-row">
            <li class="nav-item mr-auto">
                <a class="navbar-brand" href="../../../starter-kit/ltr/vertical-menu-template/">
                    <h2 class="brand-text">Games Exchange</h2>
                </a>
            </li>
            <li class="nav-item nav-toggle">
                <a class="nav-link modern-nav-toggle pr-0" data-toggle="collapse">
                    <i class="d-block d-xl-none text-primary toggle-icon font-medium-4" data-feather="x"></i>
                    <i class="d-none d-xl-block collapse-toggle-icon font-medium-4  text-primary" data-feather="disc" data-ticon="disc"></i>
                </a>
            </li>
        </ul>
    </div>
    <div class="shadow-bottom"></div>
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            <li class="nav-item @(ViewData["ActiveMenu"] == "HOME" ? "active" : "")">
                <a class="d-flex align-items-center" href="@Url.Action("Index", "Home")"><i data-feather="circle"></i><span class="menu-title text-truncate" data-i18n="Atendimento">Home</span></a>
            </li>
            <li class="nav-item @(ViewData["ActiveMenu"] == "GAMES" ? "active" : "")">
                <a class="d-flex align-items-center" href="@Url.Action("Index", "Games")"><i data-feather="circle"></i><span class="menu-title text-truncate" data-i18n="Hóspedes">Games</span></a>
            </li>
            <li class="nav-item @(ViewData["ActiveMenu"] == "FRIENDS" ? "active" : "")">
                <a class="d-flex align-items-center" href="@Url.Action("Index", "Friends")"><i data-feather="circle"></i><span class="menu-title text-truncate" data-i18n="Comercial">Amigos</span></a>
            </li>
            <li class="nav-item @(ViewData["ActiveMenu"] == "USERS" ? "active" : "")">
                <a class="d-flex align-items-center" href="@Url.Action("Index", "Users")"><i data-feather="circle"></i><span class="menu-title text-truncate" data-i18n="Financeiro">Usuários</span></a>
            </li>
        </ul>
    </div>
</div>
<!-- END: Main Menu-->

src/GamesExchange/src/GamesExchange.WebMvc/Views/Shared/_Pagination.cshtml
@model PaginationViewModel;
@{
    var modPage = Model.Summary.TotalRows % Model.Summary.PageSize;
    var maxPage = Model.Summary.TotalRows / Model.Summary.PageSize;
    maxPage = modPage == 0 ? maxPage : maxPage + 1;
}
<div class="card-body">
    <div class="row">
        <div class="col align-self-center">
            <nav aria-label="Page navigation">
                <ul class="pagination mb-1">
                    @for (var currentpage = 1; currentpage <= maxPage; currentpage++)
                    {
                        <li class="page-item @(currentpage==Model.Summary.PageNumber ? "active" : "")">
                            <a class="page-link" href="@string.Format("{0}&summary.PageNumber={1}&summary.PageSize={2}",Model.Url, currentpage, Model.Summary.PageSize)">@currentpage</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
</div>